const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_FROM_CART = "REMOVE_FROM_CART";
const INCREMENT = "INCREMENT";
const DECREMENT = "DECREMENT";
const CLEAR_CART = "CLEAR_CART";

export { ADD_TO_CART, REMOVE_FROM_CART, INCREMENT, DECREMENT, CLEAR_CART };
